Fix scripts.

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -16,7 +16,7 @@ PRJ_DIR=$SCRIPT_DIR/..
 #
 
 function unit {
-    cd ..
+    cd $PRJ_DIR
     # enable app virtual environment
     eval "$(direnv export bash)"
     if [ !$PYTHONPATH ]; then
@@ -37,30 +37,24 @@ function unit {
 }
 
 function e2e {
+    cd $PRJ_DIR
+    # enable app virtual environment
+    eval "$(direnv export bash)"
+    if [ !$PYTHONPATH ]; then
+        export PYTHONPATH=$PWD
+    fi
     echo ""
-    echo "Integration tests not implemented."
+
     echo ""
-    e2e_result=0
+    echo "Starting integration tests..."
+    echo ""
 
-    # echo ""
-    # echo "Starting integration tests..."
-    # echo ""
-    # # go to test app dir
-    # cd $PRJ_DIR/tests/integration
-
-    # # enable app virtual environment
-    # eval "$(direnv export bash)"
-    # if [ !$PYTHONPATH ]; then
-    #     export PYTHONPATH=$PWD
-    # fi
-    # echo ""
-
-    # # run integration tests & save exit code
-    # cd test
-    # python -m unittest -b $@
-    # # save exit code from tests
-    # e2e_result=$?
-    # echo ""
+    # run unit tests & save exit code
+    cd $PRJ_DIR/tests/integration
+    python -m unittest -b $@
+    # save exit code from tests
+    e2e_result=$?
+    echo ""
 }
 
 # Run unit tests or integration tests if one is specified
diff --git a/scripts/typecheck b/scripts/typecheck
--- a/scripts/typecheck
+++ b/scripts/typecheck
@@ -29,22 +29,11 @@ function check {
     mypy hoops
     mypy_src_result=$?
 
-    if [ $mypy_src_result != 0 ]; then
-        echo "Error in typechecking, see output above."
-        exit $mypy_src_result
-    fi
-
-
     echo ""
-    echo "Checking ./test..."
+    echo "Checking ./tests..."
     echo ""
-    mypy test
+    mypy tests
     mypy_tests_result=$?
-
-    if [ $mypy_tests_result != 0 ]; then
-        echo "Error in typechecking, see output above."
-        exit $mypy_tests_result
-    fi
 
     # return to scripts directory
     cd $SCRIPT_DIR
@@ -52,3 +41,11 @@ function check {
 }
 
 check
+
+if [ $mypy_src_result != 0 ]; then
+    echo "Error in typechecking application, see output above."
+    exit $mypy_src_result
+elif [ $mypy_tests_result != 0 ]; then
+    echo "Error in typechecking tests, see output above."
+    exit $mypy_tests_result
+fi
